# Generated by Django 2.2 on 2019-04-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magaz', '0012_auto_20190417_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magaz.Products', verbose_name='Id товара')),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Склад',
            },
        ),
    ]
