# Generated by Django 2.2 on 2019-04-15 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0002_auto_20190415_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='magaz.Attributes', verbose_name='Аттрибуты'),
        ),
    ]
