# Generated by Django 2.2 on 2019-04-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0004_auto_20190415_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(related_name='products', to='magaz.Products', verbose_name='Товар'),
        ),
    ]
