# Generated by Django 2.2 on 2019-04-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0005_auto_20190415_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='attribute',
            new_name='attributes',
        ),
    ]
