# Generated by Django 2.2 on 2019-04-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0008_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='isAvailable',
            field=models.BooleanField(default=1, verbose_name='Наличие на складе'),
            preserve_default=False,
        ),
    ]
