# Generated by Django 2.2 on 2019-04-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0009_products_isavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='isAvailable',
            field=models.BooleanField(choices=[('В наличии', 'В наличии'), ('Нет в наличии', 'Нет в наличии')], verbose_name='Наличие на складе'),
        ),
    ]
