# Generated by Django 2.2 on 2019-04-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0010_auto_20190417_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='isAvailable',
            field=models.BooleanField(choices=[('Yes', 'В наличии'), ('No', 'Нет в наличии')], verbose_name='Наличие на складе'),
        ),
    ]
