# Generated by Django 2.2 on 2019-04-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0011_auto_20190417_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='isAvailable',
            field=models.CharField(choices=[('Yes', 'В наличии'), ('No', 'Нет в наличии')], max_length=20, verbose_name='Наличие на складе'),
        ),
    ]
