# Generated by Django 2.2 on 2019-04-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0012_auto_20190417_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=1, help_text='Не более 1 мб', upload_to='media/', verbose_name='Карточка'),
            preserve_default=False,
        ),
    ]
