# Generated by Django 2.2 on 2019-04-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0013_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Bill', 'verbose_name_plural': 'Чек'},
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(help_text='Не более 1 мб', upload_to='media/', verbose_name='Изображение'),
        ),
    ]
