# Generated by Django 2.2 on 2019-04-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0014_auto_20190418_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='product_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='product_id',
            field=models.ManyToManyField(to='magaz.Products', verbose_name='id товара'),
        ),
    ]
