# Generated by Django 2.2 on 2019-04-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0015_auto_20190418_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='isAvailable',
            field=models.CharField(choices=[('В наличии', 'В наличии'), ('Нет в наличии', 'Нет в наличии')], max_length=20, verbose_name='Наличие на складе'),
        ),
    ]
