# Generated by Django 2.2 on 2019-05-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0017_auto_20190506_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='seil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Скидка'),
        ),
    ]
