# Generated by Django 2.2 on 2019-05-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0018_auto_20190506_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='seil',
            field=models.BooleanField(blank=True, verbose_name='Скидка'),
        ),
    ]
