# Generated by Django 2.2 on 2019-05-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0019_auto_20190506_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='seil',
        ),
    ]
