# Generated by Django 2.2 on 2019-05-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0020_remove_products_seil'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seil',
            field=models.BooleanField(blank=True, default=1, verbose_name='Скидка'),
            preserve_default=False,
        ),
    ]
