# Generated by Django 2.2 on 2019-05-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0021_products_seil'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_notseil',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8, verbose_name='Цена без скидки'),
            preserve_default=False,
        ),
    ]
