# Generated by Django 2.2 on 2019-05-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0023_auto_20190511_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='product_id',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dostavka', models.BooleanField(default=True, verbose_name='Доставка')),
                ('pub_date', models.DateTimeField()),
                ('order_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('product', models.ManyToManyField(to='magaz.Products', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='magaz.Order', verbose_name='ID заказа'),
            preserve_default=False,
        ),
    ]
