# Generated by Django 2.2 on 2019-05-11 09:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0024_auto_20190511_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='product_id',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='totalsum',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
