# Generated by Django 2.2 on 2019-05-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0025_auto_20190511_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='product', to='magaz.Products', verbose_name='Товары'),
        ),
    ]
