# Generated by Django 2.2 on 2019-05-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0027_remove_order_order_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
