# Generated by Django 2.2 on 2019-05-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0029_auto_20190511_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_int',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
