# Generated by Django 2.2 on 2019-05-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0030_products_price_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price_int',
        ),
        migrations.AddField(
            model_name='products',
            name='col',
            field=models.IntegerField(default=1, help_text='НЕ ТРОГАТЬ!', verbose_name='Количество'),
        ),
    ]
