# Generated by Django 2.2 on 2019-05-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0031_auto_20190514_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не более 50 символов', max_length=50, verbose_name='Название')),
                ('description', models.CharField(help_text='не более 150 символов', max_length=150, verbose_name='Описание бренда')),
            ],
            options={
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(related_name='category_products', to='magaz.Products', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='products',
            name='brands',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='magaz.Brands', verbose_name='Брэнд'),
            preserve_default=False,
        ),
    ]
