# Generated by Django 2.2 on 2019-05-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0032_auto_20190518_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brands',
        ),
        migrations.AddField(
            model_name='brands',
            name='products',
            field=models.ManyToManyField(related_name='products', to='magaz.Products', verbose_name='Товары'),
        ),
    ]
