# Generated by Django 2.2 on 2019-05-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0033_auto_20190518_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_notseil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена без скидки'),
        ),
    ]
