# Generated by Django 2.2 on 2019-05-31 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0034_auto_20190518_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(help_text='Не более 1 мб', upload_to='media/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magaz.Picture', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magaz.Products'),
        ),
    ]
