# Generated by Django 2.2 on 2019-06-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0038_auto_20190605_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='image',
            new_name='image_inline',
        ),
    ]
